/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#24a375",
        "surface-tint": "#545f73",
        "secondary": "#904d00",
        "surface-container-highest": "#e0e3e5",
        "on-surface-variant": "#45474c",
        "surface-container": "#eceef0",
        "tertiary": "#00190e",
        "inverse-on-surface": "#eff1f3",
        "surface": "#f7f9fb",
        "inverse-primary": "#bcc7de",
        "tertiary-fixed-dim": "#68dba9",
        "outline-variant": "#c5c6cd",
        "on-secondary-fixed": "#2f1500",
        "error": "#ba1a1a",
        "on-secondary-container": "#663500",
        "secondary-fixed-dim": "#ffb77d",
        "on-surface": "#191c1e",
        "on-background": "#191c1e",
        "on-tertiary-fixed-variant": "#005137",
        "secondary-container": "#fe932c",
        "surface-container-high": "#e6e8ea",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#d8dadc",
        "outline": "#75777d",
        "surface-bright": "#f7f9fb",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#111c2d",
        "surface-container-low": "#f2f4f6",
        "on-primary-container": "#8590a6",
        "on-secondary-fixed-variant": "#6e3900",
        "on-primary-fixed-variant": "#3c475a",
        "primary": "#091426",
        "on-tertiary-fixed": "#002114",
        "background": "#f7f9fb",
        "secondary-fixed": "#ffdcc3",
        "primary-container": "#1e293b",
        "surface-variant": "#e0e3e5",
        "tertiary-container": "#00301f",
        "primary-fixed": "#d8e3fb",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "inverse-surface": "#2d3133",
        "tertiary-fixed": "#85f8c4",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#bcc7de",
        "error-container": "#ffdad6"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin": "1rem",
        "margin-tablet": "2rem",
        "space-md": "1rem",
        "space-xl": "2.5rem",
        "space-xs": "0.25rem",
        "gutter-tablet": "1.5rem",
        "gutter-desktop": "2rem",
        "space-sm": "0.5rem",
        "margin-desktop": "3rem",
        "gutter": "1rem",
        "space-lg": "1.5rem"
      },
      fontFamily: {
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Noto Sans", "sans-serif"],
        "audio-timestamp": ["Noto Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Noto Sans", "sans-serif"],
        "label-lg": ["Noto Sans", "sans-serif"],
        "display": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Noto Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Noto Sans", "sans-serif"]
      },
      fontSize: {
        "headline-lg-mobile": ["22px", { "lineHeight": "28px", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "audio-timestamp": ["12px", { "lineHeight": "16px", "fontWeight": "700" }],
        "headline-sm": ["18px", { "lineHeight": "24px", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "label-lg": ["15px", { "lineHeight": "20px", "fontWeight": "600" }],
        "display": ["32px", { "lineHeight": "40px", "fontWeight": "700" }],
        "label-md": ["13px", { "lineHeight": "18px", "fontWeight": "600" }],
        "headline-lg": ["26px", { "lineHeight": "34px", "fontWeight": "700" }],
        "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "500" }]
      }
    }
  },
  plugins: [],
}
